name: CI

on: [push, pull_request]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@v1

    - name: Test
      run: deno test -A

    - name: deno.land/x publish
      if: startsWith(github.ref, 'refs/tags/')
      use: denoland/publish@v1

    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Get tag version
      if: startsWith(github.ref, 'refs/tags/')
      id: get_tag_version
      run: echo ::set-output name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}
    - name: npm build
      run: deno task build:npm ${{steps.get_tag_version.outputs.TAG_VERSION}}
    - name: npm publish
      if: startsWith(github.ref, 'refs/tags/')
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        cd npm
        npm publish
